server:
  port: 12342

spring:
  application:
    name: ts-user-service
  data:
    mongodb:
      host: ts-user-mongo
      database: ts-user-mongo
      port: 27017

swagger:
  controllerPackage: user.controller

logging:
  file: logs/ts-user-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG