server:
  port: 18885  # HTTP (Tomcat) port

spring:
  application:
    name: ts-cancel-service

swagger:
  controllerPackage: cancel.controller

logging:
  file: logs/ts-cancel-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG