server:
  port: 15678  # HTTP (Tomcat) port

spring:

  application:
    name: ts-verification-code-service

swagger:
  controllerPackage: verifycode.controller

logging:
  file: logs/ts-verification-code-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG