# HTTP Server
server:
  port: 12346  # HTTP (Tomcat) port

spring:
  application:
    name: ts-travel-service
  data:
    mongodb:
      host: ts-travel-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017
swagger:
  controllerPackage: travel.controller

logging:
  file: logs/ts-travel-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG