#spring:
#  data:
#    mongodb:
#      host: ts-preserve-other-mongo
##      username: user
##      password: ${MONGODB_PASSWORD}
##      database: piggymetrics
#      port: 27017

# HTTP Server
server:
  port: 14569 # HTTP (Tomcat) port

spring:
  application:
    name: ts-preserve-other-service
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}

swagger:
  controllerPackage: preserveOther.controller

logging:
  file: logs/ts-preserve-other-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG