server:
  port: 12340
spring:
  application:
    name: ts-auth-service
  data:
    mongodb:
      host: ts-auth-mongo
      database: ts-auth-mongo
      port: 27017

swagger:
  controllerPackage: auth.controller

logging:
  file: logs/ts-auth-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG