server:
  port: 12347

spring:
  application:
    name: ts-contacts-service
  data:
    mongodb:
      host: ts-contacts-mongo
      database: ts
      port: 27017

swagger:
  controllerPackage: contacts.controller

logging:
  file: logs/ts-contacts-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG