spring:
  application:
    name: ts-consign-price-service
  data:
    mongodb:
      host: ts-consign-price-mongo
      database: ts
      port: 27017


# HTTP Server
server:
  port: 16110

swagger:
  controllerPackage: consignprice.controller

logging:
  file: logs/ts-consign-price-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG