server:
  port: 12386

spring:
  application:
    name: ts-execute-service
swagger:
  controllerPackage: execute.controller

logging:
  file: logs/ts-execute-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG