server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service


swagger:
  controllerPackage: adminorder.controller

logging:
  file: logs/ts-admin-order-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG