# HTTP Server
server:
  port: 12031  # HTTP (Tomcat) port

spring:
  application:
    name: ts-order-service
  data:
    mongodb:
      host: ts-order-mongo
#      username: user
#      password: ${MONGODB_PASSWORD}
      database: ts
      port: 27017

swagger:
  controllerPackage: order.controller

logging:
  file: logs/ts-order-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG