server:
  port: 16114

spring:
  application:
    name: ts-admin-travel-service

swagger:
  controllerPackage: admintravel.controller

logging:
  file: logs/ts-admin-travel-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG