# HTTP Server
server:
  port: 15681  # HTTP (Tomcat) port

spring:
  application:
    name: ts-ticketinfo-service


swagger:
  controllerPackage: ticketinfo.controller

logging:
  file: logs/ts-ticketinfo-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG