server:
  port: 18898

spring:
  application:
    name: ts-seat-service

swagger:
  controllerPackage: seat.controller

logging:
  file: logs/ts-seat-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG