server:
  port: 18808

spring:
  application:
    name: ts-delivery-service
  data:
    mongodb:
      host: ${mongohost:ts-delivery-mongo}
      database: ts
      port: 27017
  rabbitmq:
    host: ${rabbitmq_host:localhost}
    port: ${rabbitmq_port:5672}

logging:
  file: logs/ts-delivery-service.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    fdse.microservice: DEBUG
